// Every user-facing UI string, by key (spec §6.4). Dialogue, notes, glossary, bios and other
// story text live in chapter content, not here. {placeholders} are filled by t(key, vars).
export const EN = {
  'game.title': 'Kaibigan',
  'game.subtitle': 'A Noli Me Tangere Story',

  'title.continue': 'Continue',
  'title.continueSub': 'Magpatuloy',
  'title.newGame': 'New Game',
  'title.enterCode': 'Enter Code',
  'title.saveDiscarded': "Couldn't load your save, starting fresh",

  'letter.nameLabel': 'Sign with your name',
  'letter.titleLabel': 'You are',
  'letter.sign': 'Sign',
  'letter.nameError.empty': 'Please write your name.',
  'letter.nameError.long': 'Please keep your name to 20 letters or fewer.',
  'letter.nameError.chars': 'Please use letters, spaces, apostrophes or hyphens only.',

  'code.heading': 'Enter your save code',
  'code.wordsLabel': 'Code words',
  'code.nameLabel': 'Your name',
  'code.submit': 'Continue',
  'code.back': 'Back',
  'code.error.empty': 'Please type the words of your code.',
  'code.error.unknownWord': "I don't recognize the word '{word}' (word {position}).",
  'code.error.ambiguousWord': "The word '{word}' (word {position}) could be more than one word. Please type more of it.",
  'code.error.length': 'This code has the wrong number of words. A code has {count} words.',
  'code.error.checksum': "Something's wrong with this code. Please check the words.",
  'code.error.newerVersion': 'This code is from a newer version of the game',
  'code.error.unknownCheckpoint': "This code is for a part of the story this version doesn't have yet.",

  'hud.controls': 'WASD / arrows: move · Shift: run · Space / E: talk · J: journal · M: mute · Esc: menu · H: hide',
  'hud.time.dusk': 'Dusk',
  'hud.time.evening': 'Evening',
  'hud.time.night': 'Night',

  'dialogue.next': 'Next',
  'glossary.close': 'Close',

  'journal.title': 'Journal',
  'journal.tab.characters': 'Characters',
  'journal.tab.notes': 'Notes',
  'journal.notesCount': '{found} of {total} found',
  'journal.feelings': 'Things you sense',
  'journal.empty': 'Nothing yet.',
  'journal.close': 'Close',

  'toast.journal': 'Journal updated',
  'toast.lowFps': 'Running slowly? Set Graphics to Low in the menu (Esc).',

  'kodigo.heading': 'Save Code (Kodigo)',
  'kodigo.copy': 'Copy',
  'kodigo.copied': 'Copied',
  'kodigo.hint': 'Write this down to continue on any device.',
  'kodigo.none': 'No save code yet. One appears at the start of each part of the story.',
  'kodigo.close': 'Close',

  'menu.title': 'Menu',
  'menu.resume': 'Resume',
  'menu.quality': 'Graphics',
  'menu.quality.low': 'Low',
  'menu.quality.high': 'High',
  'menu.textSpeed': 'Text speed',
  'menu.textSpeed.slow': 'Slow',
  'menu.textSpeed.normal': 'Normal',
  'menu.textSpeed.fast': 'Fast',
  'menu.textSpeed.instant': 'Instant',
  'menu.volume': 'Volume',
  'menu.mute': 'Sound',
  'menu.mute.on': 'Off',
  'menu.mute.off': 'On',
  'menu.saveCode': 'Show save code',
  'menu.resetPosition': 'Reset position',
  'menu.quit': 'Quit to title',

  'end.heading': 'End of Chapter {chapter}',
  'end.recap': 'What happened',
  'end.notes': 'Notes found: {found} of {total}',
  'end.standing': 'Where you stand',
  'end.think': 'Think about it',
  'end.code': 'Your save code',
  'end.continue': 'Continue',

  'touch.talk': 'Talk',
  'touch.journal': 'Journal',
  'touch.menu': 'Menu',

  'fatal.webgl': "Sorry, this browser can't run the game (WebGL is unavailable). Try a recent Chrome, Edge, Firefox or Safari.",
  'error.banner': 'Something went wrong: {message}',
};
