// Save-code words (spec §3.9). FROZEN: never reorder, edit or remove a word once shipped;
// codes depend on each word's position. 509 is prime, which makes the checksum exact.
export const WORDS = Object.freeze([
  'abo', 'adobo', 'agila', 'agos', 'ahas', 'akasya', 'aklat', 'alaala', 'alab', 'alimango',
  'alon', 'ama', 'ambon', 'ampalaya', 'anak', 'anim', 'anino', 'apat', 'apoy', 'araro',
  'araw', 'asin', 'asotea', 'asukal', 'asul', 'awit', 'baboy', 'bagwis', 'bagyo', 'bahagi',
  'bahay', 'bait', 'baka', 'bakod', 'bakuran', 'balat', 'balete', 'balik', 'balikat', 'banaba',
  'bango', 'bangus', 'banig', 'bansa', 'bantay', 'barko', 'batis', 'bato', 'baul', 'bawang',
  'bayabas', 'bayan', 'baybay', 'bayong', 'benta', 'berde', 'bibig', 'bibingka', 'bigay', 'biko',
  'bili', 'binata', 'binondo', 'bintana', 'binti', 'bituin', 'biyernes', 'biyolin', 'bola', 'bote',
  'braso', 'bubong', 'bubuyog', 'buhangin', 'buhok', 'bukas', 'bukid', 'bundok', 'bunga', 'burol',
  'butiki', 'butil', 'buwan', 'buwaya', 'daan', 'dagat', 'dahon', 'dakila', 'dalaga', 'dalandan',
  'daliri', 'damdamin', 'damit', 'damo', 'dangal', 'dapitan', 'dasal', 'datu', 'daungan', 'dayuhan',
  'dilaw', 'dilim', 'dingding', 'diwa', 'diwata', 'duhat', 'dunong', 'gabay', 'gabi', 'gagamba',
  'galak', 'galing', 'gamot', 'ganda', 'gatas', 'gawain', 'giliw', 'ginhawa', 'gising', 'gitara',
  'gubat', 'gulong', 'gumamela', 'gunita', 'gunting', 'guro', 'hagdan', 'halaman', 'hamog', 'hanap',
  'handog', 'hangin', 'hapag', 'harana', 'hardin', 'hari', 'hasa', 'hatid', 'hawak', 'higa',
  'hikaw', 'himig', 'hintay', 'hipon', 'hiram', 'hiyas', 'husay', 'huwebes', 'ibon', 'ikot',
  'ilog', 'ina', 'ingat', 'init', 'inom', 'ipil', 'isda', 'isip', 'itim', 'kaba',
  'kabayo', 'kahapon', 'kahel', 'kaibigan', 'kakanin', 'kalabasa', 'kalabaw', 'kalamba', 'kalapati', 'kalaw',
  'kalayaan', 'kaldero', 'kalesa', 'kaliwa', 'kalye', 'kamatis', 'kamay', 'kambing', 'kamia', 'kamote',
  'kampana', 'kampo', 'kandado', 'kandila', 'kanin', 'kanta', 'kapatid', 'kape', 'karayom', 'karitela',
  'kasoy', 'katha', 'kawali', 'kawayan', 'keso', 'kidlat', 'kinang', 'kislap', 'korona', 'kubo',
  'kuhol', 'kulambo', 'kulog', 'kumbento', 'kumot', 'kundiman', 'kuneho', 'kusina', 'kuta', 'kutsara',
  'kutsero', 'kuwago', 'kuwarto', 'kuwento', 'kuwintas', 'labanos', 'lagari', 'laguna', 'lahi', 'lakas',
  'lakbay', 'lamig', 'lamok', 'lampara', 'landas', 'langaw', 'langgam', 'langit', 'langka', 'langoy',
  'lansones', 'lapis', 'larawan', 'laro', 'laruan', 'lawa', 'lawin', 'layag', 'leeg', 'libro',
  'ligaya', 'liham', 'likha', 'lila', 'lindol', 'linggo', 'linis', 'lipad', 'litson', 'liwanag',
  'lolo', 'loob', 'lubid', 'lugaw', 'lumpia', 'lundag', 'lunes', 'lungsod', 'lupa', 'lutas',
  'luto', 'maalat', 'maasim', 'mababa', 'mabagal', 'mabigat', 'mabilis', 'madilim', 'magaan', 'maganda',
  'mahal', 'mahina', 'maikli', 'maingay', 'mainit', 'mais', 'makapal', 'makata', 'makopa', 'malakas',
  'malaki', 'malambot', 'malamig', 'malapit', 'malayo', 'maliit', 'malinis', 'mananahi', 'mangga', 'mangkok',
  'mani', 'manika', 'manipis', 'manok', 'mansanas', 'mapait', 'martes', 'martilyo', 'masaya', 'mataas',
  'matamis', 'matapang', 'matigas', 'maya', 'maynila', 'mesa', 'mithi', 'musika', 'narra', 'nayon',
  'ngalan', 'ngipin', 'ngiti', 'ningas', 'ningning', 'niyog', 'noo', 'oras', 'orasan', 'paa',
  'paaralan', 'pader', 'pagong', 'pako', 'paksa', 'palaka', 'palay', 'palayok', 'palengke', 'palitaw',
  'pamana', 'pamaypay', 'pampang', 'panata', 'panday', 'pangako', 'pangarap', 'paniki', 'pansit', 'pantalan',
  'panyo', 'papaya', 'papel', 'parada', 'parang', 'parol', 'paruparo', 'pasig', 'patak', 'pating',
  'pawis', 'perlas', 'pilak', 'pinggan', 'pinsan', 'pinto', 'pinya', 'pipino', 'pisngi', 'pista',
  'piyano', 'plasa', 'plato', 'plauta', 'pluma', 'poso', 'prinsipe', 'pugad', 'pulot', 'pulseras',
  'punla', 'puno', 'puri', 'pusa', 'pusit', 'putik', 'rambutan', 'regalo', 'reyna', 'rosas',
  'sabado', 'sabaw', 'sagana', 'saging', 'saglit', 'sagot', 'sagwan', 'sahig', 'sakahan', 'sakay',
  'saklaw', 'salakot', 'salamat', 'salamin', 'salita', 'sampay', 'sampu', 'sandali', 'sandok', 'sanga',
  'santol', 'sapa', 'sapatos', 'sapin', 'sibuyas', 'sigla', 'silid', 'silong', 'silya', 'simbahan',
  'simoy', 'sinag', 'singsing', 'sinigang', 'sining', 'sinulid', 'sipol', 'sitaw', 'siyam', 'sobre',
  'sombrero', 'sorbetes', 'suha', 'sulat', 'sulo', 'sulyap', 'suman', 'sundo', 'sungka', 'susi',
  'taas', 'tadhana', 'tagal', 'tagumpay', 'tahanan', 'tahimik', 'tainga', 'takbo', 'takip', 'takure',
  'tala', 'talaan', 'talaba', 'talim', 'talino', 'talong', 'tambol', 'tamis', 'tanaw', 'tanghali',
  'tanglaw', 'taniman', 'tanso', 'taon', 'tapang', 'tatlo', 'tawid', 'tibay', 'timba', 'timbang',
  'tinapay', 'tindahan', 'tingin', 'tinidor', 'tinig', 'tinola', 'tinta', 'tirahan', 'tito', 'tiwala',
  'tiyaga', 'tore', 'toyo', 'trumpo', 'tsinelas', 'tubig', 'tugtog', 'tuhod', 'tulay', 'tuldok',
  'tunog', 'turon', 'tutubi', 'tuwa', 'ubas', 'ugali', 'ugat', 'ugnay', 'ulap', 'umaga',
  'unan', 'unggoy', 'unlad', 'upo', 'upuan', 'usbong', 'usok', 'utos', 'uwak', 'wagas',
  'walis', 'walo', 'wasto', 'watawat', 'wika', 'yakap', 'yaman', 'yelo', 'yugto',
]);
